# Configuration file to declaratively configure labels
# Ref: https://github.com/EndBug/label-sync#Config-files

# TODO: enable this when we have a release/v1.0.x branch
#- name: backport:release/v1.0.x
#  description: To be backported to release/v1.0.x
#  color: '#ffd700'
